# Generated by Django 4.2.4 on 2023-09-17 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_remove_event_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='customer',
        ),
        migrations.AddField(
            model_name='book',
            name='address',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.event'),
        ),
        migrations.AddField(
            model_name='book',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
