# Generated by Django 4.2.4 on 2023-09-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_book_customer_book_address_book_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
